import React, { useState } from "react";

import InstagramMessagesPage from "./InstagramMessages";
import SignIn from "./sign-in";

import { signOut } from "firebase/auth";

import Cookies from "universal-cookie";
import { auth } from "firebase-config";

const cookies = new Cookies();

const Home = () => {
  // const [user] = useAuthState(auth);

  const [isAuth, setIsAuth] = useState(cookies.get("auth-token"));
  const [isInChat, setIsInChat] = useState(null);
  const [room, setRoom] = useState("");

  if (!isAuth) {
    return <SignIn setIsAuth={setIsAuth} />;
  }

  const signUserOut = async () => {
    await signOut(auth);
    cookies.remove("auth-token");
    setIsAuth(false);
    setIsInChat(false);
  };

  return (
    <>
      <div className="App ">
        {/* <header>
          <h1>⚛️🔥💬</h1>
          <button onClick={signUserOut}> Sign Out</button>
        </header> */}

        <section className="">
          {" "}
          <InstagramMessagesPage />{" "}
        </section>
      </div>

      {/* <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link
            to="/instagrammessages"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            InstagramMessages
          </Link>
        </li>
      </ul>
    </div> */}
    </>
  );
};
export default Home;
